RESTful API
frdedynamics/student-project-corona pull request #15
Opened 2020-04-13 21:11 UTC by haggbart

Postman collection import link: https://www.getpostman.com/collections/3ce412c56c60311862c4

2020-04-16 18:08 UTC, haggbart commented
Disabling testing on windows because there's no support for uwsgi.
May look into special requirements for windows as uwsgi is only needed for deployment.
#17

2020-04-23 16:03 UTC, haggbart commented
#closing 18
don't build on windows

2020-04-23 16:04 UTC, haggbart commented
closing #18 
don't build on windows

2020-05-01 14:57 UTC, MOJOliciousFTW commented
funka fett med postman, men kom ingen vei med student-project-corona-ui. 401 ingen access token. Hadde access token i header. Interveven foreslo WSGIPassAuthorization on og då gav eg opp http://lopezpino.com/2017/04/03/flask-jwt-authorization-and-wsgi/

2020-05-01 15:06 UTC, haggbart commented
Skjønner. Tenkte å gå over til jwt-extended som gir litt flere muligheter, dessuten er ikke flask jwt oppdatert på en stund, ser ut som den er erstattet fullstendig. Men planen nå blir å gjøre eksamen først 😅 

Kanskje jeg skal lære meg litt javascript også, får sjå.

2020-05-01 17:44 UTC, MOJOliciousFTW commented
bah, la til att CORS so fikk eg tilgang. Veit ikkje om det er ei god løysing.

2020-05-01 17:46 UTC, MOJOliciousFTW commented on app.py
> +from flask_jwt import JWT
```suggestion
from flask_jwt import JWT
from flask_cors import CORS
```

2020-05-01 17:47 UTC, MOJOliciousFTW commented on app.py
> +
```suggestion
CORS(app)
```

2020-05-01 17:51 UTC, MOJOliciousFTW requested changes
I request the cors changes so I don`t need to do much with the ui testing

2020-05-01 17:59 UTC, haggbart commented
kan godt hende, må sette meg inn i cors

2020-05-02 10:57 UTC, merged